substitutions:
  onboard_led_id: ${id}_onboard_led
  led_rgb_id: ${id}_onboard_led
  # needed substitutions:
  # id:

# packages needed by available-script:
#   onboard-led

esphome:
  on_boot:
    - priority: 600
      then:
        - logger.log: "Boot - init - LED blue dimmed"
        - light.turn_on:
            <<: !include ./snippets/color-presets_any_led-rgb/blue.yaml
            brightness: 10%
            transition_length: 0ms
        - delay: 500ms
        - light.turn_on:
            <<: !include ./snippets/color-presets_any_led-rgb/blue.yaml
            brightness: 100%
            transition_length: 1500ms
        - logger.log: "Boot - problem with wifi - LED blue"
    - priority: 240
      then:
        - logger.log: "Boot - wifi established - LED cyan dimmed"
        - light.turn_on:
            <<: !include ./snippets/color-presets_any_led-rgb/cyan.yaml
            brightness: 10%
    - priority: 200
      then:
        - logger.log: "Boot - api connected - LED green dimmed"
        - light.turn_on:
            <<: !include ./snippets/color-presets_any_led-rgb/green.yaml
            brightness: 10%
        - delay: 500ms
        - light.turn_off:
            <<: !include ./snippets/color-presets_any_led-rgb/_off.yaml
        - logger.log:
            format: "Boot - initialized - LED off"
            level: INFO
