substitutions:
  # needed substitutions:
  # id:

switch:
  - platform: template
    name: "Bed Light"
    id: ${id}_bed_light
    lambda: |-
      if (id(some_binary_sensor).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
      - switch.turn_on: ${id}_relay1_bed_light_left
      - switch.turn_on: ${id}_relay1_bed_light_right
    turn_off_action:
      - switch.turn_off: ${id}_relay1_bed_light_left
      - switch.turn_off: ${id}_relay1_bed_light_right
  - platform: gpio
    name: Bed Light Left
    id: ${id}_relay1_bed_light_left
    icon: mdi:bed-double-outline
    pin: 
      number: GPIO3
      inverted: true
    restore_mode: ALWAYS_OFF
    device_class: switch
  - platform: gpio
    name: Bed Light Right
    id: ${id}_relay2_bed_light_right
    icon: mdi:bed-double-outline
    pin: 
      number: GPIO4
      inverted: true
    restore_mode: ALWAYS_OFF
    device_class: switch
  - platform: gpio
    name: Relay3
    id: ${id}_relay3
    icon: mdi:electric-switch
    pin: 
      number: GPIO1
      inverted: true
    restore_mode: ALWAYS_OFF
    device_class: switch
    internal: true
  - platform: gpio
    name: Relay4
    id: ${id}_relay4
    icon: mdi:electric-switch
    pin: 
      number: GPIO0
      inverted: true
    restore_mode: ALWAYS_OFF
    device_class: switch
    internal: true
