substitutions:
  # needed substitutions:
  # id:

switch:
  - platform: gpio
    name: Bed Light Left
    id: ${id}_relay1_bed_light_left
    icon: mdi:bed-double-outline
    pin: GPIO3
  - platform: gpio
    name: Bed Light Right
    id: ${id}_relay2_bed_light_right
    icon: mdi:bed-double-outline
    pin: GPIO4
  - platform: gpio
    name: Relay3
    id: ${id}_relay3
    icon: mdi:electric-switch
    pin: GPIO0
  - platform: gpio
    name: Bed Light Right
    id: ${id}_relay4
    icon: mdi:electric-switch
    pin: GPIO1
