substitutions:
  name: electrical-meter
  id: electrical_meter
  name_verbose: Electrical Meter
  name_old: ${name} # change for renameing a device
  # pins
  helper_binary_pin: GPIO35
  helper_adc_pin: GPIO32
  id_control_led_pin: GPIO21
  # secrets
  ota_pw: !secret ota_pw
  wifi_home_ssid: !secret wifi_home_ssid
  wifi_home_pw: !secret wifi_home_pw
  wifi_fallback_pw: !secret wifi_fallback_pw

packages:
  board: !include /config/boards/az-delivery-devkitc-v4.yaml
  git-version: !include /config/packages/git-version.yaml
  wifi: !include /config/packages/wifi.yaml
  common-defaults: !include /config/packages/common-defaults.yaml
  diagnostic-sensors: !include /config/packages/diagnostic-sensors.yaml
  # specific
  energy-tick-counter: !include /config/packages/sensors/integrator/energy-tick-counter.yaml
