substitutions:
  name: electrical-meter
  id: electrical_meter
  name_verbose: Electrical Meter
  # secrets
  ota_pw: !secret ota_pw
  wifi_home_ssid: !secret wifi_home_ssid
  wifi_home_pw: !secret wifi_home_pw
  wifi_fallback_pw: !secret wifi_fallback_pw

packages:
  electrical-meter: !include /config/presets/az-delivery/esp32-devkitc-v4/electrical-meter.yaml
