substitutions:
  # use with "-s location sleep -s location_verbose Sleep" or other locations respective
  # currently available: sleep,Sleep|office,Office
  name: environment-mm-${location}
  id: environment_mm_${location}
  name_verbose: Environment ElaMax ${location_verbose}
  i2c_bus_a_sda: '4'
  i2c_bus_a_scl: '3'

  ota_pw: !secret ota_pw
  wifi_home_ssid: !secret wifi_home_ssid
  wifi_home_pw: !secret wifi_home_pw
  wifi_fallback_pw: !secret wifi_fallback_pw
  mqtt_broker: !secret mqtt_broker
  mqtt_port: !secret mqtt_port
  mqtt_user: !secret mqtt_user
  mqtt_pw: !secret mqtt_pw

packages:
  board: !include common/boards/m5stack-stamp-c3u.yaml
  wifi: !include common/wifi.yaml
  mqtt: !include common/mqtt.yaml
  i2c: !include common/i2c_a.yaml

sensor:
  - <<: !include common/sensors/bme280.yaml # connected via i2c_a
