substitutions:
  name: environment-mm-sleep
  id: environment_mm_sleep
  name_verbose: Environment MM Sleeping Room

esphome:
  name: $name
  platformio_options:
    board_build.flash_mode: dio
    platform_packages:
     - toolchain-riscv32-esp @ 8.4.0+2021r1
     - toolchain-xtensa-esp32s2 @ 8.4.0+2021r1

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: esp-idf

# Enable logging
logger:
  hardware_uart: USB_SERIAL_JTAG

mqtt:
  broker: 192.168.178.69
  port: 1883
  client_id: $name
  username: !secret mqtt_user
  password: !secret mqtt_pw

sensor:
  - platform: dht
    model: DHT22
    pin: G3
    temperature:
      name: "$name_verbose Temperature"
      accuracy_decimals: 1
    humidity:
      name: "$name_verbose Humidity"
      accuracy_decimals: 1
    update_interval: 60s

ota:
  password: !secret ota_pw

wifi:
  ssid: !secret wifi_home_ssid
  password: !secret wifi_home_pw
  ap: # Enable fallback hotspot (captive portal) in case wifi connection fails
    ssid: $name
    password: !secret wifi_fallback_pw

preferences:
  flash_write_interval: 10min
