#!/bin/bash

SCRIPT_DIR="$(dirname -- $(readlink -fn -- "$0"))"
source "${SCRIPT_DIR}/.env"
ARGS=$@

NONE='\e[0m'
RED='\e[31m'
GREEN='\e[32m'
YELLOW='\e[33m'
BLUE='\e[34m'

COMMANDS=('run' 'upload' 'rename')
for c in "${COMMANDS[@]}"; do
	if printf '%s\0' "$ARGS" | grep -Fqz -- "$c"; then
        # check git status when calling one of $COMMANDS
        if GIT_STATUS=$(git status --porcelain) && [ -n "$GIT_STATUS" ]; then
            echo -e "You have ${YELLOW}uncommited changes${NONE}:"
            git status --short
            read -p $'Do you want to \e[34mproceed\e[0m? (\e[33myN\e[0m): ' YN
            case $YN in 
                y ) echo -e "${GREEN}Proceeding${NONE}...\n";;
                * ) echo -e "${RED}Aborted${NONE}";
                    exit 1;;
            esac
        fi
        echo -e "Appending ${BLUE}version${NONE} to args."
        ARGS=( "-s" "version" "${GIT_VERSION}" ${ARGS[@]} )
        break
    fi
done

CONTAINER_PROGRAM=""
if ! command -v podman &> /dev/null ; then
    if ! command -v docker &> /dev/null ; then
        echo -e "Container ${RED}podman or docker${NONE} could not be found!"
        exit 2
    else
        CONTAINER_PROGRAM="docker"
    fi
else
    CONTAINER_PROGRAM="podman"
fi

"${CONTAINER_PROGRAM}" run --rm -v "${SCRIPT_DIR}:/config" -it "${ESPHOME_CONTAINER}:${ESPHOME_TAG}" ${ARGS[@]}
