#!/bin/bash

SCRIPT_DIR="$(dirname -- $(readlink -fn -- "$0"))"
source "${SCRIPT_DIR}/.env"

DOCKER_ARGS=()
ESPHOME_ARGS=()

for arg in "$@"; do
    if [[ "$arg" =~ ^--device=.* ]]; then
        DOCKER_ARGS+=("$arg")
    elif [[ "$arg" =~ ^--net=.* ]]; then
        DOCKER_ARGS+=("$arg")
    else
        ESPHOME_ARGS+=("$arg")
    fi
done

COMMANDS=('run' 'upload' 'rename' 'config' 'compile' 'clean')
for c in "${COMMANDS[@]}"; do
	if printf '%s\0' "$ESPHOME_ARGS" | grep -Fqz -- "$c"; then
        # check git status when calling one of $COMMANDS
        if GIT_STATUS=$(git status --porcelain) && [ -n "$GIT_STATUS" ]; then
            echo -e "You have ${YELLOW}uncommited changes${NONE}:"
            git status --short
            read -p $'Do you want to \e[34mproceed\e[0m? (\e[33myN\e[0m): ' YN
            case $YN in
                y ) echo -e "${GREEN}Proceeding${NONE}...\n";;
                * ) echo -e "${RED}Aborted${NONE}";
                    exit 1;;
            esac
        fi
        echo -e "Appending ${BLUE}version${NONE} to esphome args."
        ESPHOME_ARGS=( "-s" "version" "${GIT_VERSION}" ${ESPHOME_ARGS[@]} )
        break
    fi
done

"${CONTAINER_PROGRAM}" run ${DOCKER_ARGS[@]} --rm -v "${SCRIPT_DIR}:/config" -it "${ESPHOME_CONTAINER}:${ESPHOME_TAG}" ${ESPHOME_ARGS[@]}
