substitutions:
  sensor_id: ${id}_energy_total
  global_id: ${sensor_id}_value
  helper_sensor: ${sensor_id}_raw
  helper_adc_id: ${helper_sensor}_adc
  helper_binary_id: ${helper_sensor}_binary
  # needed substitutions:
  # name_verbose:
  # id:
  # helper_adc_pin:
  # id_control_led_pin:

packages:
  control-led: !include /config/packages/control-led.yaml

api:
  services:
    - service: set_${sensor_id}
      variables:
        value: float
      then:
        - globals.set:
            id: ${global_id}
            value: !lambda 'return value;'
        - component.update: ${sensor_id}

logger:
  logs:
    sensor.${helper_adc_id}: ERROR

globals:
  - id: ${global_id}
    type: float
    restore_value: no
    initial_value: '0.0'

sensor:
  - name: ${name_verbose} Energy Total
    id: ${sensor_id}
    platform: template
    unit_of_measurement: kWh
    accuracy_decimals: 2
    lambda: return id(${global_id});
    update_interval: 60s

  - id: ${helper_adc_id}
    platform: adc
    pin: ${helper_adc_pin}
    update_interval: 10ms
    raw: true
    internal: true
    unit_of_measurement: ''
    filters:
      - multiply: 0.00024420024     # 1/(2^12-1)

binary_sensor:
  - platform: analog_threshold
    id: ${helper_binary_id}
    sensor_id: ${helper_adc_id}
    threshold:
      upper: 0.9999
      lower: 0.7
    filters:
      - delayed_on: 50ms
    on_release:
      - globals.set:
          id: ${global_id}
          value: !lambda 'return id(${global_id}) + 0.01;'
      - light.toggle:
          id: ${id_control_led}
      - component.update: ${sensor_id}
