substitutions:
  # preset defaults
  log_level: DEBUG
  binary_counter_pin: GPIO35
  analog_counter_pin: GPIO32
  control_led_pin: GPIO21

# api:
#   services:
#     - service: set_${id}_pulse_total
#       variables:
#         new_pulse_total: int
#       then:
#         - pulse_counter.set_total_pulses:
#             # id: ${id}_pulse_counter_power
#             id: ${id}_pulse_meter_power
#             value: !lambda 'return new_pulse_total;'

packages:
  board: !include /config/common/boards/az-delivery-devkitc-v4.yaml
  wifi: !include /config/common/wifi.yaml
  mqtt: !include /config/common/mqtt.yaml
  web_server: !include /config/common/web_server.yaml

<<: !include /config/common/lights/control-led.yaml

sensor:
  # - <<: !include /config/common/sensors/power_pulse_counter.yaml
  - <<: !include /config/common/sensors/power_pulse_meter.yaml
  # - name: ${name_verbose} ADC
  #   id: ${id}_adc
  #   platform: adc
  #   pin: ${analog_counter_pin}
  #   update_interval: 100ms
  #   raw: true
  #   unit_of_measurement: ""
  #   filters:
  #     - multiply: 0.00024420024 # 1/(2^12-1)
