esphome:
  name: ${name}
  min_version: '2022.11'

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

logger:
  level: ${log_level}

captive_portal:

preferences:
  flash_write_interval: 10min
