# arduino works currently only with docker.io/esphome/esphome:dev build
# it should be available in docker.io/esphome/esphome:2022.12
esphome:
  name: ${name}
  min_version: '2022.12'
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3
    platform_packages:
      - platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.5
  <<: !include /config/common/actions/m5stack/stamp-c3u/boot-led.yaml

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

logger:
  level: ${log_level}

preferences:
  flash_write_interval: 10min

light:
  - <<: !include /config/common/lights/m5stack-stamp-c3u-onboard-led.yaml
