substitutions:
  log_level: DEBUG
  flash_write_interval: 10min
  # needed substitutions:

logger:
  level: ${log_level}

api:

preferences:
  flash_write_interval: ${flash_write_interval}

web_server:
  port: 80
  ota: false
