substitutions:
  id_control_led: ${id}_control_led
  # needed substitutions:
  # id:
  # name:
  # id_control_led_pin:

light:
  - platform: binary
    name: ${name}-control-led
    id: ${id_control_led}
    output: ${id_control_led}_output
    entity_category: diagnostic

output:
  - id: ${id_control_led}_output
    platform: gpio
    pin: ${id_control_led_pin}
