substitutions:
  control_led_id: ${id}_control_led
  # needed substitutions:
  # id:
  # name:
  # control_led_pin:

light:
  - platform: binary
    name: ${name} Control Led
    id: ${control_led_id}
    internal: true
    output: ${control_led_id}_output
    entity_category: diagnostic

output:
  - id: ${control_led_id}_output
    platform: gpio
    pin: ${control_led_pin}
