substitutions:
  # needed substitutions:
  # id:
  # name_verbose:

binary_sensor:
  - # max' hardware button (physical)
    name: ${name_verbose} Bed Button Max
    id: ${id}_button_max
    icon: mdi:toggle-switch
    platform: gpio
    pin:
      number: GPIO20 # brown
      inverted: true
      mode:
        input: true
        pullup: true
    entity_category: diagnostic
    filters:
      - delayed_on_off: 50ms
    on_multi_click:
    - timing:
        - ON for at most 500ms
        - OFF for 60ms to 500ms
        - ON for at most 500ms
        - OFF for at least 60ms
      then:
        - logger.log: bed button Max short double-clicked
        - switch.toggle: ${id}_bed_light
    - timing:
        - ON for 1s to 3s
        - OFF for 60ms to 1s
        - ON for 1s to 3s
        - OFF for at least 60ms
      then:
        - logger.log: bed button Max long double-clicked
        - switch.toggle: ${id}_relay1
  - # elas hardware button (physical)
    name: ${name_verbose} Bed Button Ela
    id: ${id}_button_ela
    icon: mdi:toggle-switch
    platform: gpio
    pin:
      number: GPIO21 # green
      inverted: true
      mode:
        input: true
        pullup: true
    entity_category: diagnostic
    filters:
      - delayed_on_off: 50ms
    on_multi_click:
    - timing:
        - ON for at most 500ms
        - OFF for 60ms to 500ms
        - ON for at most 500ms
        - OFF for at least 60ms
      then:
        - logger.log: bed button Ela short double-clicked
        - switch.toggle: ${id}_bed_light
    - timing:
        - ON for 1s to 3s
        - OFF for 60ms to 1s
        - ON for 1s to 3s
        - OFF for at least 60ms
      then:
        - logger.log: bed button Ela long double-clicked
        - switch.toggle: ${id}_relay2

switch:
  - # combined bed lights (logical)
    name: ${name_verbose} Bed Light
    id: ${id}_bed_light
    icon: mdi:bed-double
    platform: template
    turn_on_action:
      - switch.turn_on: ${id}_relay1
      - switch.turn_on: ${id}_relay2
    turn_off_action:
      - switch.turn_off: ${id}_relay1
      - switch.turn_off: ${id}_relay2
  - # max' bed side only (physical)
    name: ${name_verbose} Bed Light Max
    id: ${id}_relay1
    icon: mdi:bed-double-outline
    platform: gpio
    pin:
      number: GPIO3 # blue
      inverted: true
    restore_mode: ALWAYS_OFF
    device_class: switch
    on_turn_on:
      - if:
          condition:
            switch.is_on: ${id}_relay2
          then:
            - lambda: id(${id}_bed_light).publish_state(true);
    on_turn_off:
      - if:
          condition:
            switch.is_off: ${id}_relay2
          then:
            - lambda: id(${id}_bed_light).publish_state(false);
  - # elas bed side only (physical)
    name: ${name_verbose} Bed Light Ela
    id: ${id}_relay2
    icon: mdi:bed-double-outline
    platform: gpio
    pin:
      number: GPIO4 # green
      inverted: true
    restore_mode: ALWAYS_OFF
    device_class: switch
    on_turn_on:
      - if:
          condition:
            switch.is_on: ${id}_relay1
          then:
            - lambda: id(${id}_bed_light).publish_state(true);
    on_turn_off:
      - if:
          condition:
            switch.is_off: ${id}_relay1
          then:
            - lambda: id(${id}_bed_light).publish_state(false);
  - # currently unused relay
    name: Relay3
    id: ${id}_relay3
    icon: mdi:electric-switch
    platform: gpio
    pin:
      number: GPIO1 # yellow
      inverted: true
    restore_mode: ALWAYS_OFF
    device_class: switch
    internal: true
  - # currently unused relay
    name: Relay4
    id: ${id}_relay4
    platform: gpio
    icon: mdi:electric-switch
    pin:
      number: GPIO0 # grey
      inverted: true
    restore_mode: ALWAYS_OFF
    device_class: switch
    internal: true
